services:
  front:
    image: node:22
    ports:
      - 5173:5173
    volumes:
      - ./shop/front:/app
    working_dir: /app
    command: npm run dev
  server:
    build:
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 8081:8080
    depends_on:
      - database
    links:
      - database
  database:
    image: mongo:7
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:
